-- Preset == testing
-- i dont think you can run this beautified
--[[ This file was generated by ObscuraLua, a Lua obfuscator that provides a wide range of features to protect your code. ]] --
local a, b
do
    local function c(a)
        local b = ""
        for c = 1, #a, 1 do
            b = b .. a[c]
        end
        return b
    end
    local d = math.floor
    local e = math.random
    local f = table
    local g = f.remove
    local h = string.char
    local i = 0
    local j = 2
    local k = {}
    local l = {}
    local m = 0
    local n = f.create(256)
    for a = 1, 256, 1 do
        n[a] = a
    end
    repeat
        local a = e(1, #n)
        local b = g(n, a)
        l[b] = h(b - 1)
    until #n == 0
    local o = {}
    local function p()
        if #o == 0 then
            i = (i * 226293 + 84252871) % 4294967296
            repeat
                j = (j * 156) % 257
            until j ~= 1
            local a = j % 32
            local b = (d(i / 2 ^ (13 - (j - a) / 32)) % 4294967296) / 2 ^ a
            local c = d((b % 1) * 4294967296) + d(b)
            local e = c % 65536
            local f = (c - e) / 65536
            local g = e % 256
            local h = (e - g) / 256
            local k = f % 256
            local l = (f - k) / 256
            o = {g, h, k, l}
        end
        return g(o)
    end
    local q = {}
    a = setmetatable({}, {__index = q, __metatable = nil})
    function b(a, b)
        local d = q
        local e = 61764
        if not d[b] then
            o = {}
            local f = l
            i = b % 4294967296
            j = b % 255 + 2
            local g = #a
            local h = {}
            for b = 1, g, 1 do
                local c = a:byte(b)
                e = ((c + p()) + e) % 256
                h[b] = f[e + 1]
            end
            d[b] = c(h)
        end
        if type(d[b]) == f then
            local a = d[b]
            local c = ""
            for b = 1, #a, 1 do
                local d = a:sub(b, b)
                local f = d:byte()
                local g = (f - (p() + e)) % 256
                c = c .. l[g + 1]
            end
            d[b] = c
        end
        return b
    end
end
local c = a[b("\078\061\a\245\144", 2481232216)]
local d = a[b("\019\205~\162\172", 2474068229)]
local e = c .. (a[b("\080\252", 1812078990)] .. (d .. a[b("\221", 2000212107)]))
print(a[b("\225\a\026\117\253\224\114\198\203\116\041~\060\051\223\001\216\137\093\211\230", 2040665123)] .. e)
local f = #e
print(a[b("\192\209\041\249\048\093\056\041\167\186\074\163\249\099\083\012\082\243\253\026\114\020", 1476338904)] .. f)
local g = string[a[b("\038\051\113", 251502193)]](e, 1, 5)
print(a[b("\014\087\050\209\056\092\247\094\249\055\052", 955908955)] .. g)
local h = string[a[b("\129\251\180\144\208", 3247446438)]](e)
local i = string[a[b("\247\003\222\164\217", 2156862286)]](e)
print(a[b("\143\171\000\103\060\202\202\017\228\211\250", 2323160211)] .. h)
print(a[b("\161\003\a\168\221\241\109\088\146\t\038", 2138445511)] .. i)
local j, k = string[a[b("\033'\233\105", 2156038031)]](e, a[b("\083\023\147\143\248", 2759771716)])
if j then
    print(
        a[
            b(
                "\227\086\131\003\078\154\206\121\004\066\072\121\160\252\064\137\044\079\115\239\150\005\237\114\151\124\227",
                1426823679
            )
        ] ..
            (j .. (a[b("\064\084\207\146", 2512864569)] .. k))
    )
else
    print(a[b("\099\190\210 \058\199\223\095\078\252\065\192\146\193\006\240\246\154", 4200673870)])
end
local l =
    string[a[b("\180\044\235\137", 3715315647)]](
    e,
    a[b("\072\111\199\247\185", 482263161)],
    a[b("\068\041\036", 556043026)]
)
print(a[b("\217\195\a\040\220\023\138\015\158\012\106\254\018\133\218\107\182", 823254430)] .. l)
print(
    a[b("\252\070\155\005\253~\017\216\109\025\160\030\250\245\109\148\025\187\075\035\144\004\005\248\015", 4211821567)]
)
for c = 1, #e, 1 do
    local d = string[a[b("\018\076\237", 3849549707)]](e, c, c)
    print(a[b("\041\243\129\n\035\002\017\215\219\174", 3171436477)] .. (c .. (a[b("\166\130", 1375301487)] .. d)))
end
local m = {}
for c in string[a[b("\090\055\244\016\235\254", 3351524300)]](e, a[b("\057\082\063", 2171791090)]) do
    table[a[b("\a\059\197\240\033\066", 3397712911)]](m, c)
end
print(a[b("\019\250\040\130\015\052\197\033\219\082\212\247\141\130\059\254\183\242\104\213", 2440540071)])
for c, d in ipairs(m) do
    print(a[b("\019\022\246\184\185", 3320038330)] .. (c .. (a[b("\245\105", 1290308919)] .. d)))
end
