-- Preset == testing

--[[ This file was generated by ObscuraLua, a Lua obfuscator that provides a wide range of features to protect your code. ]] --
local a, b
do
    local function c(a)
        local b = ""
        for c = 1, #a, 1 do
            b = b .. a[c]
        end
        return b
    end
    local d = math.floor
    local e = math.random
    local f = table
    local g = f.remove
    local h = string.char
    local i = 0
    local j = 2
    local k = {}
    local l = {}
    local m = 0
    local n = f.create(256)
    for a = 1, 256, 1 do
        n[a] = a
    end
    repeat
        local a = e(1, #n)
        local b = g(n, a)
        l[b] = h(b - 1)
    until #n == 0
    local o = {}
    local function p()
        if #o == 0 then
            i = (i * 159101 + 5153111203) % 4294967296
            repeat
                j = (j * 149) % 257
            until j ~= 1
            local a = j % 32
            local b = (d(i / 2 ^ (13 - (j - a) / 32)) % 4294967296) / 2 ^ a
            local c = d((b % 1) * 4294967296) + d(b)
            local e = c % 65536
            local f = (c - e) / 65536
            local g = e % 256
            local h = (e - g) / 256
            local k = f % 256
            local l = (f - k) / 256
            o = {g, h, k, l}
        end
        return g(o)
    end
    local q = {}
    b = setmetatable({}, {__index = q, __metatable = nil})
    function a(a, b)
        local d = q
        local e = 9658
        if not d[b] then
            o = {}
            local f = l
            i = b % 4294967296
            j = b % 255 + 2
            local g = #a
            local h = {}
            for b = 1, g, 1 do
                local c = a:byte(b)
                e = ((c + p()) + e) % 256
                h[b] = f[e + 1]
            end
            d[b] = c(h)
        end
        if type(d[b]) == f then
            local a = d[b]
            local c = ""
            for b = 1, #a, 1 do
                local d = a:sub(b, b)
                local f = d:byte()
                local g = (f - (p() + e)) % 256
                c = c .. l[g + 1]
            end
            d[b] = c
        end
        return b
    end
end
print(b[a("\137\042\069\026\133\254\173\022\001\102\117\202\107\071\049\248", 3240208151)])
local c = 100000
print(b[a("\075\171\216\038\239\003\196\214\229\005\176\234", 984057007)] .. tostring(c))
local d = {[b[a("\137\248\206\178\082\253\193", 694596263)]] = function()
        for c = 1, c, 1 do
            (function()
                if false then
                    print(b[a("\159\233\012\165\055\153\140\141\224~", 2487884446)])
                end
            end)()
        end
    end, [b[a("\t\229\020\136\195\179\058\249", 1450876566)]] = function()
        local d = {}
        for c = 1, c, 1 do
            d[tostring(c)] = b[a("\231\v\243\200\099\018\174\076\024\n\194", 1419404845)] .. tostring(c)
        end
    end, [b[a("\227\134\012\229\237\019\n\002", 3268651418)]] = function()
        local a = {}
        for b = 1, c, 1 do
            a[1] = a[tostring(b)]
        end
    end, [b[a("\140\r\230\094\081\244\094\243\089\017\040\n\254", 3097649694)]] = function()
        local function a()
        end
        for b = 1, c, 1 do
            a()
        end
    end, [b[a("\082\033\247\089\115\170\248\014\049\250", 3544396062)]] = function()
        local a = 0
        for b = 1, c, 1 do
            a = a + b
        end
    end, [b[a("\121\001\128\228\065\064\041-\244\000\136\131\042\078\245\072\071\070\254", 13518808)]] = function()
        local d = b[a("", 865018071)]
        for a = 1, c, 1 do
            d = d .. tostring(a)
        end
    end}
local e = os[b[a("\186\166\055\056", 1615027769)]]()
for c, d in pairs(d) do
    print(c .. b[a("'\120\001\001\001\041\075\233\140", 2113392142)])
    local e = os[b[a("\161\117\158\108", 1727008759)]]()
    d()
    print(
        b[a("\033\053\002\074\096", 4032300625)],
        os[b[a("\245\185\196\247", 23153411)]]() - e .. b[a("\058", 290200551)]
    )
end
print(
    b[a("\135\084\037\236\201\233\052\006\180\248\196", 1800023756)],
    os[b[a("\234\245\166\196", 459797147)]]() - e .. b[a("\219", 2187579974)]
)
